name: Github Actions Controller

on:
  workflow_dispatch:
    inputs:
      pull_testing:
        description: 'Pull testing workflows'
        type: boolean
        default: false
      pull_linting:
        description: 'Pull linting workflows'
        type: boolean
        default: false
      pull_build:
        description: 'Pull build workflows'
        type: boolean
        default: false
      pull_deployment:
        description: 'Pull deployment workflows'
        type: boolean
        default: false

jobs:
  update-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Pull workflows from controller
        uses: BenFielder/github-actions-controller@v1.19.0
        with:
          pull_testing_workflows: ${{ inputs.pull_testing }}
          pull_linting_workflows: ${{ inputs.pull_linting }}
          pull_build_workflows: ${{ inputs.pull_build }}
          pull_deployment_workflows: ${{ inputs.pull_deployment }}
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}